config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get :search, controller: :home
  get :users, controller: :home
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'

  resources :question_threads do
    resources :answers, module: :question_threads
  end

  resources :answers, only: [] do
    resources :comments, module: :question_threads
  end

  resources :accepted_answers, only: [:create], module: :question_threads

  resources :chatrooms do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question_thread.rb
# == Schema Information
#
# Table name: question_threads
#
#  id                 :bigint(8)        not null, primary key
#  details            :text
#  question           :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  accepted_answer_id :integer
#  chatroom_id        :integer
#  user_id            :integer
#

class QuestionThread < ApplicationRecord
  after_save :send_mentions!

  belongs_to :user
  has_many :answers
  has_many :comments, :through => :answers
  has_many :users, :through => :answers
  has_one :chatroom

  validates :question, presence: true
  validates :details, presence: true

  def send_notifications!
    users = question_thread.users.uniq - [user]
    users.each do |user|
      NotificationMailer.question_notification(user, self).deliver_later
    end
  end

  def send_mentions!
    Mentions.send_notification_emails(:details, self)
  end
end

app/controllers/question_threads/accepted_answers_controller.rb
class QuestionThreads::AcceptedAnswersController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  before_action :set_question_thread, only: [:create]

  # TODO: Consider changing this to update method
  def create
    @question_thread.accepted_answer_id = accepted_answer_params[:answer_id]
    if @question_thread.save
      redirect_to question_thread_url(accepted_answer_params[:question_thread_id], notice: "Saved as accepted answer")
    else
      redirect_to question_thread_url(accepted_answer_params[:question_thread_id], notice: "Unable to save as accepted")
    end
  end

    private

      def accepted_answer_params
        params.permit(:answer_id, :question_thread_id)
      end

      def set_question_thread
        @question_thread = QuestionThread.find(accepted_answer_params[:question_thread_id])
      end
end

app/controllers/question_threads/answers_controller.rb
class QuestionThreads::AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_question_thread
  before_action :set_answer, only: [:update]

	def create
		@answer = @question_thread.answers.new answer_params
		@answer.user = current_user

    if @answer.save
      @answer.send_notifications!
      redirect_to question_thread_path(@question_thread, anchor: "answer-#{@answer.id}"),
                  notice: "Successfully posted!"
    else
      redirect_to @question_thread, alert: "Unable to save your post"
    end
  end

	def update
    respond_to do |format|
      if @answer.update answer_params
        @answer.send_notifications!
        format.html { redirect_to question_thread_path(@question_thread, anchor: "answer-#{@answer.id}"),
                    notice: "Successfully updated!" }
        format.js
      else
        format.html { redirect_to @question_thread, alert: "Unable to save your post" }
        format.js
      end
    end
  end

	private 

    def set_question_thread
      @question_thread = QuestionThread.find(params[:question_thread_id])
    end

    def set_answer
      @answer = Answer.find(params[:id])
    end

		def answer_params
			params.require(:answer).permit(:body)
		end
end

app/controllers/question_threads/comments_controller.rb
class QuestionThreads::CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_answer
  before_action :set_comment, only: [:update]

  def create
		@comment = @answer.comments.new comment_params
		@comment.user = current_user

    respond_to do |format|
    if @comment.save
        @comment.send_notifications!
        format.html { redirect_to question_thread_path(@answer.question_thread_id), notice: "Successfully posted!" }
        format.js
      else
        format.html { redirect_to question_thread_path(@answer.question_thread_id), alert: "Unable to save your comment" }
      end
    end
  end

  def update
    respond_to do |format|
      if @comment.update comment_params
        @comment.send_notifications!
        format.html { redirect_to question_thread_path(@answer.question_thread_id), notice: "Updated comment!" }
        format.js
      else
        format.html { redirect_to question_thread_path(@answer.question_thread_id), alert: "Unable to save your comment" }

      end
    end
  end

  private

    def set_answer
      @answer = Answer.find(params[:answer_id])
    end

    def set_comment
      @comment = Comment.find(params[:id])
    end

		def comment_params
			params.require(:comment).permit(:body)
		end

end

app/controllers/question_threads_controller.rb
class QuestionThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question_thread, except: [:index, :new, :create]
  before_action :set_chatroom, only: [:show]
  before_action :set_chatroom_user, only: [:show]

  def index
    @question_threads = QuestionThread.all
  end

  def show
		@answer = Answer.new
		answers = Answer.where(question_thread_id: @question_thread.id)
    acceptedAnswerId = @question_thread.accepted_answer_id
    @accepted_answer = answers.to_a.select { |a| a.id == acceptedAnswerId }
    @answers = answers.to_a.reject { |a| a.id == acceptedAnswerId }
  end

  def new
    @question_thread = QuestionThread.new
    @question_thread.answers.new
  end

  def create
    @question_thread = current_user.question_threads.new question_thread_params

    if @question_thread.save
      @chatroom = Chatroom.new(name: "Chatroom #{@question_thread.id}", question_thread_id: @question_thread.id)
      if @chatroom.save
        redirect_to @question_thread, notice: "Successfully created!"
      end
    else
      redirect_to question_thread_path(@question_thread), alert: "Unable to create your question"
    end
  end

  def update
    if @question_thread.update question_thread_params
      @question_thread.send_notifications!
      redirect_to question_thread_path(@question_thread), notice: "Successfully updated!"
    else
      redirect_to @question_thread, alert: "Unable to save your post"
    end
  end
  
  private
    
    def set_question_thread
      @question_thread = QuestionThread.find(params[:id])
    end

    def set_chatroom
      @chatroom = Chatroom.find_by(question_thread_id: params[:id])
      @chatroom.messages.order(created_at: :desc).limit(100).reverse
    end

    def set_chatroom_user
      if user_signed_in?
        @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first_or_create
      end
    end

    def question_thread_params
      params.require(:question_thread).permit(:question, :details) 
    end
end

app/views/question_threads/_edit_question.html.erb
<%= form_for question_thread, html: {class: "#{toggleDisplay}"}, data: { target: "inline-edit.form"}, :remote => true  do |f| %>
  <div class="form-group">
    <%= f.text_field :question, placeholder: "Question", class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.text_area :details, data: { behavior: "mentions" }, placeholder: "Details", rows: 10, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit :class => "btn btn-primary form-control" %>
  </div>

  <%= submit_tag 'Close', type: 'button', class: "btn btn-secondary col", data: { action: "click->inline-edit#hideForm"} %>
<% end %>

app/views/question_threads/_form.html.erb
<%= form_for @question_thread do |f| %>
  <div class="form-group">
    <%= f.text_field :question, placeholder: "Question", class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.text_area :details, data: { behavior: "mentions" }, placeholder: "Details", rows: 10, class: "form-control" %>
  </div>
 <div class="form-group">
    <%= f.submit :class => "btn btn-primary form-control" %>
  </div>
<% end %>

app/views/question_threads/_question_thread.html.erb
<%= link_to question_thread do %>
  <h3><%= question_thread.question %></h3>
<% end %>

app/views/question_threads/index.html.erb
  <div class="row">
    <div class="col">
      <h1 class="page-header">Browse Questions</h1>
    </div>

  </div>
  <% if user_signed_in? %>
    <div class="row">
      <div class="col">
        <%= link_to "New Question", new_question_thread_path, class: "btn btn-success" %>
      </div>
    </div>
  <% end %>
  <hr>

  <%= render @question_threads %>

app/views/question_threads/new.html.erb
<h1>New Question</h1>

<%= render "form" %>

app/views/question_threads/show.html.erb
<div class="row">

  <div class="col-6 chatSidebar">
    <%= render partial: "chatrooms/chatroom", locals: { chatroom: @chatroom } %>
  </div>

  <div class="col-6 question">

    <div data-controller="inline-edit">
      <% if user_signed_in? and @question_thread.user_id == current_user.id %>
        <h1 data-action="click->inline-edit#showForm"><%= @question_thread.question %></h1>
        <%= render partial: "question_threads/edit_question", method: :patch,  locals: {
            question_thread: @question_thread, toggleDisplay: "d-none"  } %>
      <% else %>
        <h1><%= @question_thread.question %></h1>
      <% end %>

      <div class="text-muted">Asked by <%= @question_thread.user.name %></div>

      <% if user_signed_in? and @question_thread.user_id == current_user.id %>
        <div data-target="inline-edit.body" data-action="click->inline-edit#showForm"><%= @question_thread.details %></div>
        <%= render partial: "question_threads/edit_question", method: :patch,  locals: {
            question_thread: @question_thread, toggleDisplay: "d-none"  } %>
      <% else %>
        <div><%= @question_thread.details %></div>
      <% end %>
    </div>


    <% if not @accepted_answer.empty? %>
      <%= render partial: "question_threads/accepted_answers/accepted_answer" %>
    <% end %>

    <div id="answers">
      <% @answers.each do |answer| %>

        <%= render partial: "question_threads/answers/answer", locals:{answer: answer} %>

        <% answer.comments.each do |comment| %>
          <%= render partial: "question_threads/comments/comment", locals:{answer: answer, comment: comment} %>
        <% end %>

        <div class="row" id="addComment-<%= answer.id.to_s %>">
          <div class="col addComment">
            <% if user_signed_in? %>
              <%= render partial: "question_threads/comments/form", locals:{answer: answer, comment: answer.comments.new} %>
            <% else %>
              <%= link_to "Sign in to comment", new_user_session_url %>
            <% end %>
          </div>
        </div>

      <% end %>
    </div>

    <% if user_signed_in? %>
      <%= render partial: "question_threads/answers/form" %>
    <% else %>
       <%= link_to "Sign in to answer", new_user_session_url %>
    <% end %>

  </div>

</div>