config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  namespace :admin do
      resources :users
      resources :announcements
      resources :notifications
      resources :services

      root to: "users#index"
    end
  get '/privacy', to: 'home#privacy'
  get '/terms', to: 'home#terms'
  get :search, controller: :home
  get :users, controller: :home
  resources :notifications, only: [:index]
  resources :announcements, only: [:index]
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }
  root to: 'home#index'

  resources :question_threads do
    resources :answers, module: :question_threads
  end

  resources :answers, only: [] do
    resources :comments, module: :question_threads
  end

  resources :accepted_answers, only: [:create], module: :question_threads

  resources :chatrooms do
    resources :messages
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def terms
  end

  def privacy
  end

  def search
    @questions = QuestionThread.ransack(question_or_details_cont: params[:q]).result(distinct: true)
    @messages = Message.ransack(body_cont: params[:q]).result(distinct: true)
    @answers = Answer.ransack(body_cont: params[:q]).result(distinct: true)

    respond_to do |format|
      format.html {}
      format.json {
        @questions = @questions.limit(3)
        @answers = @answers.limit(3)
        @messages = @messages.limit(3)
      }
    end
  end

  # GET /users
  # GET /users.json
  def users
    @users = User.all
  end

end

app/views/home/index.html.erb
<h1>Continuity</h1>
<p class="lead">Use this question and answer platform to help establish continuity</p>

<div class="row">
  <div class="col">
    <%= link_to "Questions", question_threads_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/home/privacy.html.erb
<h1>Privacy Policy</h1>
<p class="lead">Use this for your Privacy Policy</p>

app/views/home/search.html.erb
<div class="row">
  <div class="col">
    <h1>Question Thread</h1>
    <% @questions.each do |question| %>
      <p><%= link_to question.question, question %></p>
    <% end %>
  </div>

  <div class="col">
    <h1>Answers</h1>
    <% @answers.each do |answer| %>
      <p><%= link_to answer.body, question_thread_path(answer.question_thread_id.to_s) %></p>
    <% end %>
  </div>


  <div class="col">
    <h1>Messages</h1>
    <% @messages.each do |message| %>
      <p><%= link_to message.body, question_thread_path(message.chatroom_id.to_s) %></p>
    <% end %>
  </div>
</div>

app/views/home/terms.html.erb
<h1>Terms of Service</h1>
<p class="lead">Use this for your Terms of Service</p>